// AUTO-GENERATED by scripts/syncAvatarCatalog.js — não editar manualmente.
// Adicione imagens em icon/avatar/ e reinicie o app (npm start).

import { ImageSourcePropType } from 'react-native';

export interface AvatarOption {
  id: string;
  label: string;
  source: ImageSourcePropType;
}

export const AVATAR_OPTIONS: AvatarOption[] = [
  { id: 'homem1', label: 'Homem 1', source: require('../../icon/avatar/homem1.png') },
  { id: 'homem2', label: 'Homem 2', source: require('../../icon/avatar/homem2.png') },
  { id: 'menina1', label: 'Menina 1', source: require('../../icon/avatar/menina1.png') },
  { id: 'menina2', label: 'Menina 2', source: require('../../icon/avatar/menina2.png') },
  { id: 'menino1', label: 'Menino 1', source: require('../../icon/avatar/menino1.png') },
];

export const DEFAULT_AVATAR_PRESET = 'menino1';
