const FREQ_PT: Record<string, string> = {
  once: 'Pontual',
  daily: 'Diária',
  weekly: 'Semanal',
  monthly: 'Mensal',
  custom: 'Personalizada',
};

export function catalogEntryMatchesApproxAgeYears(entry: any, yearsApprox: any): boolean {
  if (yearsApprox == null || Number.isNaN(Number(yearsApprox))) return true;
  const y = Number(yearsApprox);
  return y >= entry.ageMin && y <= entry.ageMax;
}

export function catalogEntryToSeedDescription(entry: any): string {
  const freq = FREQ_PT[entry.frequency] || entry.frequency;
  let rec = '';
  if (entry.frequency === 'weekly' && entry.recurrence_days?.length) {
    const dias = [...entry.recurrence_days].sort((a, b) => a - b).join(', ');
    rec = ` • Dias da semana (0=Dom…6=Sáb): ${dias}`;
  }
  const bonus =
    entry.affectsAllowance && Number(entry.bonus_amount) > 0
      ? ` • Bónus mesada sugerido: até R$ ${Number(entry.bonus_amount).toFixed(2)} (combinem em família antes de ativar).`
      : '';
  const approval = entry.requiresApproval ? ' • Sugestão: confirmação dos pais quando concluída.' : '';

  return (
    `${entry.description}\n\n` +
    `— Modelo FamilyBase · Idades recomendadas: ${entry.ageMin}–${entry.ageMax} anos · ` +
    `~${entry.estimatedMin} min · ${entry.difficultyLabel} · ${freq}${rec}${bonus}${approval}`
  );
}

function T(x: any) {
  return {
    ...x,
    coins: x.coins ?? 0,
    recurrence_days: x.recurrence_days ?? [],
  };
}

export const FAMILY_TASK_TEMPLATE_CATALOG = [
  T({ slug: 'fb26_bed_5_10', ageMin: 5, ageMax: 10, category: 'Organização', title: '🛏️ Arrumar a cama', description: 'Cobrir a cama pela manhã sem perfeccionismo excessivo — hábito de ordem.', taskType: 'routine', frequency: 'daily', estimatedMin: 6, difficultyLabel: 'Leve', points: 10, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_toys_5_7', ageMin: 5, ageMax: 7, category: 'Organização', title: '🧸 Guardar os brinquedos antes do jantar', description: 'Tudo num sítio combinado — caixotes ou etiquetas ajudam a criança a lembrar-se.', taskType: 'home', frequency: 'daily', estimatedMin: 10, difficultyLabel: 'Leve', points: 12, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_shoes_8_13', ageMin: 8, ageMax: 13, category: 'Organização', title: '🥿 Calçado no lugar certo ao entrar em casa', description: 'Um micro-hábito que reduz atritos repetidos pela casa.', taskType: 'routine', frequency: 'daily', estimatedMin: 3, difficultyLabel: 'Muito rápida', points: 6, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_pack_sun', ageMin: 8, ageMax: 13, category: 'Organização', title: '🎒 Rever a mochila ao domingo', description: 'Material essencial para a semana; sem pressão máxima, só conferência rápida com um adulto se precisarem.', taskType: 'school', frequency: 'weekly', recurrence_days: [0], estimatedMin: 15, difficultyLabel: 'Médio', points: 16, requiresApproval: true, affectsAllowance: true, bonus_amount: 3 }),
  T({ slug: 'fb26_desk_teens', ageMin: 14, ageMax: 18, category: 'Organização', title: '📚 Limpar a mesa de estudo antes de estudar', description: 'Manter apenas o necessário durante o tempo de trabalho combinado.', taskType: 'school', frequency: 'daily', estimatedMin: 8, difficultyLabel: 'Médio', points: 14, requiresApproval: false, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_clothes_fold', ageMin: 11, ageMax: 18, category: 'Organização', title: '🧺 Dobrar ou pendurar a própria roupa lavada', description: 'Uma vez por semana ajuda à autonomia; os adultos também mostram como se faz nos primeiros tempos.', taskType: 'home', frequency: 'weekly', recurrence_days: [6], estimatedMin: 25, difficultyLabel: 'Médio', points: 20, requiresApproval: false, affectsAllowance: true, bonus_amount: 3 }),
  T({ slug: 'fb26_fridge_art', ageMin: 5, ageMax: 10, category: 'Organização', title: '🖼️ Escolher um desenho da semana para pendurar', description: 'Orgulho saudável; rodar evita sobrecarga de papel no frigorífico.', taskType: 'home', frequency: 'weekly', recurrence_days: [0], estimatedMin: 8, difficultyLabel: 'Leve', points: 10, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_floor_toys_quick', ageMin: 5, ageMax: 7, category: 'Limpeza', title: '🧽 “Raio rápido” — recolher o que está no chão da sala', description: '2–3 minutos com música leve opcional.', taskType: 'home', frequency: 'weekly', recurrence_days: [3], estimatedMin: 5, difficultyLabel: 'Leve', points: 9, requiresApproval: false, affectsAllowance: true, bonus_amount: 0.5 }),
  T({ slug: 'fb26_dishes_mid', ageMin: 11, ageMax: 16, category: 'Limpeza', title: '🍽️ Secar ou arrumar louça na hora combinada', description: 'Combina segurança: peças delicadas apenas com supervisão até estarem habituados.', taskType: 'home', frequency: 'weekly', recurrence_days: [2], estimatedMin: 18, difficultyLabel: 'Médio', points: 18, requiresApproval: true, affectsAllowance: true, bonus_amount: 3 }),
  T({ slug: 'fb26_sort_laundry_teens', ageMin: 14, ageMax: 18, category: 'Limpeza', title: '🧼 Separar roupa por tipo/cor antes da máquina', description: 'Habilidade útil para a vida independente mais tarde.', taskType: 'home', frequency: 'weekly', recurrence_days: [5], estimatedMin: 12, difficultyLabel: 'Médio', points: 14, requiresApproval: false, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_trash_rotate', ageMin: 8, ageMax: 13, category: 'Casa', title: '🗑️ Dia combinado para levar o saco até ao contentor', description: 'Rotação justa se houver vários filhos.', taskType: 'home', frequency: 'weekly', recurrence_days: [4], estimatedMin: 8, difficultyLabel: 'Leve', points: 11, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_eco_corner', ageMin: 14, ageMax: 18, category: 'Casa', title: '♻️ Levar pilhas ou electrónicos pequenos ao ecoponto (combinado pelo adulto)', description: 'Saúde e segurança primeiro: rota combinada antes.', taskType: 'home', frequency: 'monthly', estimatedMin: 25, difficultyLabel: 'Médio', points: 18, requiresApproval: true, affectsAllowance: true, bonus_amount: 5 }),
  T({ slug: 'fb26_wipe_surface', ageMin: 12, ageMax: 18, category: 'Limpeza', title: '🪣 Limpar uma superfície combinada da cozinha', description: 'Produtos e panos combinados sempre com a família.', taskType: 'home', frequency: 'weekly', recurrence_days: [1], estimatedMin: 12, difficultyLabel: 'Médio', points: 15, requiresApproval: true, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_windows_low', ageMin: 11, ageMax: 14, category: 'Limpeza', title: '🪟 Limpar apenas a parte inferior acessível de uma vidraça', description: 'Nada de janelas altas nem degraus instáveis — só à altura dos braços.', taskType: 'home', frequency: 'monthly', estimatedMin: 20, difficultyLabel: 'Médio', points: 16, requiresApproval: true, affectsAllowance: true, bonus_amount: 3 }),
  T({ slug: 'fb26_homework_block', ageMin: 8, ageMax: 13, category: 'Estudos', title: '📝 Tempo combinado para trabalhos de casa antes do lazer grande', description: 'Blocos curtos com um micro-descanso; telemóvel fora até acabar o combinado.', taskType: 'school', frequency: 'weekly', recurrence_days: [1, 2, 3, 4], estimatedMin: 35, difficultyLabel: 'Médio', points: 22, requiresApproval: true, affectsAllowance: true, bonus_amount: 3 }),
  T({ slug: 'fb26_homework_planeer', ageMin: 14, ageMax: 18, category: 'Estudos', title: '🧭 Planear 10 min antes de iniciar trabalhos grandes', description: 'Anotar 3 passos no papel aumenta probabilidade de concluir menos frustrados.', taskType: 'school', frequency: 'daily', estimatedMin: 10, difficultyLabel: 'Leve-hábito', points: 12, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_read_20', ageMin: 5, ageMax: 10, category: 'Estudos', title: '📖 Ler em voz alta ou silenciosa ~20 min (livro físico combinado)', description: 'Ler por prazer conta; perguntas leves apenas se combinado antes (sem interrogatório no fim).', taskType: 'school', frequency: 'daily', estimatedMin: 20, difficultyLabel: 'Leve', points: 14, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_read_30', ageMin: 11, ageMax: 18, category: 'Estudos', title: '📖 Leitura contínua combinada (~30 min, um dia da semana)', description: 'Pode incluir ficção não escolar se a meta for fluência.', taskType: 'school', frequency: 'weekly', recurrence_days: [0], estimatedMin: 30, difficultyLabel: 'Médio', points: 20, requiresApproval: false, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_revision_sun', ageMin: 14, ageMax: 18, category: 'Estudos', title: '🔎 Revisão leve aos domingo (flashcards ou resumo próprio)', description: 'Um mapa rápido de lacunas grandes — não obriga trabalho infinito.', taskType: 'school', frequency: 'weekly', recurrence_days: [0], estimatedMin: 40, difficultyLabel: 'Exigente', points: 24, requiresApproval: true, affectsAllowance: true, bonus_amount: 5 }),
  T({ slug: 'fb26_math_focus', ageMin: 13, ageMax: 18, category: 'Estudos', title: '🧊 Bloco de foco só para matemática (25–30 min)', description: 'Só uma lista combinada antes de começar — evitar saltar aos exercícios “difíceis” sem plano.', taskType: 'school', frequency: 'weekly', recurrence_days: [2], estimatedMin: 30, difficultyLabel: 'Médio', points: 22, requiresApproval: false, affectsAllowance: true, bonus_amount: 3 }),
  T({ slug: 'fb26_vocab_game', ageMin: 8, ageMax: 10, category: 'Estudos', title: '🔤 Jogo rápido de palavras (10 palavras da semana)', description: 'Brincadeira curta entre adulto e criança; errar faz parte.', taskType: 'school', frequency: 'weekly', recurrence_days: [4], estimatedMin: 12, difficultyLabel: 'Leve', points: 12, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_vocab_teen', ageMin: 14, ageMax: 18, category: 'Estudos', title: '🗂️ Revisar 15 termos próprios (outra língua ou disciplina)', description: 'Fichas físicas recomendadas — menos multitasking que apps infinitos.', taskType: 'school', frequency: 'weekly', recurrence_days: [3], estimatedMin: 18, difficultyLabel: 'Médio', points: 16, requiresApproval: false, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_no_phone_study', ageMin: 14, ageMax: 18, category: 'Comportamento', title: '📵 Sala de estudo combinada sem telemóvel próprio', description: 'Funciona quando os adultos modelam comportamento igual no mesmo espaço combinado.', taskType: 'routine', frequency: 'daily', estimatedMin: 45, difficultyLabel: 'Exigente', points: 28, requiresApproval: true, affectsAllowance: true, bonus_amount: 5 }),
  T({ slug: 'fb26_teeth_twice', ageMin: 5, ageMax: 18, category: 'Saúde', title: '🦷 Escovar os dentes pela manhã e à noite', description: 'Hábito base de saúde — sem tirar foto nem humilhar se falharem algum dia; retomamos amanhã.', taskType: 'routine', frequency: 'daily', estimatedMin: 6, difficultyLabel: 'Hábito base', points: 8, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_water_morning', ageMin: 6, ageMax: 13, category: 'Saúde', title: '🍶 Água num copo combinado já na cozinha de manhã', description: 'Pequenas garrafas acessíveis ajudam a autonomia.', taskType: 'routine', frequency: 'daily', estimatedMin: 2, difficultyLabel: 'Muito rápida', points: 6, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_screen_evening_teens', ageMin: 14, ageMax: 18, category: 'Saúde', title: '🌙 Ritual combinado antes de dormir (~30 min) com menos luz e menos telas', description: 'Foco em bem-estar, não culpa nem castigo por “falhou uma vez”.', taskType: 'routine', frequency: 'daily', estimatedMin: 30, difficultyLabel: 'Médio', points: 16, requiresApproval: true, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_outdoors', ageMin: 8, ageMax: 13, category: 'Saúde', title: '☀️ Tempo combinado lá fora (clima seguro)', description: 'Um parque, passeio rápido ou brincadeira no quintal conta.', taskType: 'routine', frequency: 'weekly', recurrence_days: [6], estimatedMin: 25, difficultyLabel: 'Leve/médio', points: 15, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_breakfast_own', ageMin: 11, ageMax: 16, category: 'Saúde', title: '🥣 Preparação simples do pequeno-almoço (combina receitas seguras)', description: 'Ferver leite ou usar fogão forte só quando a família e a maturidade o permitirem.', taskType: 'home', frequency: 'weekly', recurrence_days: [0], estimatedMin: 15, difficultyLabel: 'Médio', points: 16, requiresApproval: true, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_wakeup_kit', ageMin: 11, ageMax: 13, category: 'Rotina', title: '🎒 Checklist leve antes de sair de casa', description: 'Uniforme/carregadores/lanche combinados num post-it íman lado da porta.', taskType: 'routine', frequency: 'daily', estimatedMin: 6, difficultyLabel: 'Leve', points: 11, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_bedtime_routine_early', ageMin: 5, ageMax: 8, category: 'Rotina', title: '🌜 Pequeno ritual de dormir combinado em 3 passos', description: 'Ex.: dentes → pijama → uma história curta.', taskType: 'routine', frequency: 'daily', estimatedMin: 20, difficultyLabel: 'Médio leve', points: 11, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_plan_next_day', ageMin: 14, ageMax: 18, category: 'Rotina', title: '📝 Olhar pela agenda rápido no fim da tarde para o dia seguinte', description: 'Apenas destacar dois compromissos — não micromanagement infinito.', taskType: 'routine', frequency: 'daily', estimatedMin: 8, difficultyLabel: 'Leve', points: 13, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_polite_arrival', ageMin: 5, ageMax: 10, category: 'Comportamento', title: '👋 Saudar quem está em casa ao chegar', description: 'Micro gentileza para senso de pertença.', taskType: 'home', frequency: 'daily', estimatedMin: 1, difficultyLabel: 'Muito rápida', points: 5, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_conflict_pause', ageMin: 14, ageMax: 18, category: 'Comportamento', title: '🛑 Pausar e respirar antes de responder em alta voz quando frustrado(a)', description: 'Co-regulação: os adultos praticam o mesmo exemplo visível quando possível.', taskType: 'routine', frequency: 'weekly', recurrence_days: [6], estimatedMin: 10, difficultyLabel: 'Médio (regulação emocional)', points: 18, requiresApproval: true, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_share_game', ageMin: 8, ageMax: 12, category: 'Comportamento', title: '🎲 Propor ao irmão(ã) uma pequena atividade coop no dia combinado', description: 'Mais foco na tentativa sinceramente coop do que vitória sempre perfeita.', taskType: 'home', frequency: 'weekly', recurrence_days: [5], estimatedMin: 25, difficultyLabel: 'Médio', points: 15, requiresApproval: true, affectsAllowance: true, bonus_amount: 3 }),
  T({ slug: 'fb26_phone_meals', ageMin: 14, ageMax: 18, category: 'Comportamento', title: '🍽️ Refeição familiar sem telemóvel próprio (após combinado em família)', description: 'Valor social + escuta entre gerações; apenas se os adultos modelam igual.', taskType: 'routine', frequency: 'weekly', recurrence_days: [0], estimatedMin: 35, difficultyLabel: 'Médio forte', points: 20, requiresApproval: true, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_listen_first', ageMin: 5, ageMax: 7, category: 'Comportamento', title: '👂 Esperar até o adulto terminar de falar antes de interromper (com esforço repetido)', description: 'Ensinar modelo calmo primeiro; regressões são normais com fome ou cansaço.', taskType: 'home', frequency: 'daily', estimatedMin: 5, difficultyLabel: 'Hábito em curso', points: 10, requiresApproval: true, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_jump_dance_kids', ageMin: 5, ageMax: 10, category: 'Exercícios', title: '🎶 Três músicas alegres a saltar/dançar espaço livre seguro', description: 'Área livre de pontas afiadas; pausa rápido se ficar ofegante.', taskType: 'challenge', frequency: 'weekly', recurrence_days: [5], estimatedMin: 14, difficultyLabel: 'Divertimento ativo', points: 14, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_jump_rope_tween', ageMin: 11, ageMax: 13, category: 'Exercícios', title: '⚡ Pequenas séries de corda (calçado combinado e superfície segura)', description: 'Alongar pernas rápido antes; aumentar apenas lentamente sob orientação combinada.', taskType: 'challenge', frequency: 'weekly', recurrence_days: [2], estimatedMin: 15, difficultyLabel: 'Médio', points: 16, requiresApproval: true, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_walk_fam_teens', ageMin: 14, ageMax: 18, category: 'Exercícios', title: '🚶 Caminhada combinada (~20–30 min) com um adulto', description: 'Conversa leve faz parte da saúde social + físico.', taskType: 'routine', frequency: 'weekly', recurrence_days: [3], estimatedMin: 25, difficultyLabel: 'Médio', points: 18, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_plank_progress', ageMin: 13, ageMax: 18, category: 'Exercícios', title: '💪 Aquecimento curto combinado antes de exercícios de força na semana', description: 'Adaptar sempre à condição física e recomendações de saúde da família.', taskType: 'challenge', frequency: 'weekly', recurrence_days: [4], estimatedMin: 22, difficultyLabel: 'Médio', points: 20, requiresApproval: true, affectsAllowance: true, bonus_amount: 3 }),
  T({ slug: 'fb26_water_plants_all', ageMin: 6, ageMax: 18, category: 'Responsabilidades', title: '🪴 Regar plantas combinadas no dia combinado da semana', description: 'Não substitui plantas delicadas só da responsabilidade de um adulto.', taskType: 'home', frequency: 'weekly', recurrence_days: [1], estimatedMin: 8, difficultyLabel: 'Leve', points: 11, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_feed_pet_combo', ageMin: 10, ageMax: 16, category: 'Responsabilidades', title: '🐾 Ajudar a alimentar o animal combinado pela família', description: 'Segurança do animal sempre em primeiro lugar — sem brincadeiras na hora das refeições do pet.', taskType: 'home', frequency: 'daily', estimatedMin: 8, difficultyLabel: 'Médio leve', points: 13, requiresApproval: true, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_calendar_upd', ageMin: 14, ageMax: 18, category: 'Responsabilidades', title: '📎 Sugerir eventos grandes da escola ao calendário da família (texto combinado antes)', description: 'Resistir só partilhar com consentimento combinado antes — especialmente médico privado.', taskType: 'school', frequency: 'weekly', recurrence_days: [0], estimatedMin: 12, difficultyLabel: 'Médio', points: 18, requiresApproval: false, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_budget_micro', ageMin: 14, ageMax: 18, category: 'Responsabilidades', title: '💼 Anotar num caderno o que já gastaram da mesada combinada esse mês (sem julgar)', description: 'Foco hábitos financeiros conscientes antes de grandes culpas.', taskType: 'challenge', frequency: 'monthly', estimatedMin: 15, difficultyLabel: 'Leve hábitos', points: 15, requiresApproval: true, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_set_table_easy', ageMin: 5, ageMax: 10, category: 'Casa', title: '🍴 Ajudar a pôr a mesa (sem objetos cortantes ou pesados até combinado antes)', description: 'Participação com orgulho, não “serviços profissionais perfeitos”.', taskType: 'home', frequency: 'weekly', recurrence_days: [0], estimatedMin: 10, difficultyLabel: 'Leve', points: 12, requiresApproval: false, affectsAllowance: true, bonus_amount: 1 }),
  T({ slug: 'fb26_prep_snack_mid', ageMin: 10, ageMax: 14, category: 'Casa', title: '🍎 Montar uma merenda simples (sob avaliações seguras combinadas primeiro)', description: 'Nada de tecnologia perigosa sozinha até combinado repetidamente já treinarem.', taskType: 'home', frequency: 'weekly', recurrence_days: [3], estimatedMin: 12, difficultyLabel: 'Médio leve', points: 13, requiresApproval: true, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_carry_grocs', ageMin: 14, ageMax: 18, category: 'Casa', title: '🛒 Ajudar a trazer mantimentos combinados até casa com peso proporcional ao corpo', description: 'Hábito de coop física bem dimensionado sempre.', taskType: 'home', frequency: 'weekly', recurrence_days: [6], estimatedMin: 15, difficultyLabel: 'Médio', points: 16, requiresApproval: false, affectsAllowance: true, bonus_amount: 2 }),
  T({ slug: 'fb26_light_off_patrol', ageMin: 9, ageMax: 18, category: 'Casa', title: '💡 Roda simples antes de dormir para apagar luzes combinadas só em divisões seguríssimas', description: 'Hábito de sustentabilidade leves sem medo aos escuros combinados sempre.', taskType: 'home', frequency: 'daily', estimatedMin: 4, difficultyLabel: 'Rápida', points: 8, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_recycle_sheet', ageMin: 11, ageMax: 16, category: 'Casa', title: '♻️ Separar materiais recicláveis por categorias (papel, plástico, vidro)', description: 'Lembrete visual da família; atualizar regularmente.', taskType: 'home', frequency: 'once', estimatedMin: 25, difficultyLabel: 'Médio', points: 15, requiresApproval: true, affectsAllowance: true, bonus_amount: 3 }),
  T({ slug: 'fb26_gratitude_family', ageMin: 8, ageMax: 13, category: 'Desenvolvimento pessoal', title: '🌻 Ao domingo só duas pequenas coisas positivas escritas sobre a semana (privado)', description: 'Não obrigar a ler em voz alta — privacidade gera segurança emocional.', taskType: 'routine', frequency: 'weekly', recurrence_days: [0], estimatedMin: 8, difficultyLabel: 'Leve', points: 12, requiresApproval: false, affectsAllowance: false, bonus_amount: 0 }),
  T({ slug: 'fb26_mini_goals', ageMin: 14, ageMax: 18, category: 'Desenvolvimento pessoal', title: '🎯 No máximo dois objectivos pequenos visíveis no quarto (post-it combinado)', description: 'Listas gigantes desmotivam; celebrar só progresso repetível conta mais que perfeição imediata.', taskType: 'challenge', frequency: 'monthly', estimatedMin: 25, difficultyLabel: 'Alto planeamento', points: 22, requiresApproval: true, affectsAllowance: true, bonus_amount: 5 }),
  T({ slug: 'fb26_coping_toolbox', ageMin: 14, ageMax: 18, category: 'Desenvolvimento pessoal', title: '🛠️ Roda de estratégias calmas combinadas pela família (5 minutos)', description: 'Exemplo: música suave ouvida até acabar uma faixa curta; desenho repetido; escrever a frustração num papel e rasgar depois de estar mais calmo.', taskType: 'routine', frequency: 'weekly', recurrence_days: [5], estimatedMin: 8, difficultyLabel: 'Médio-leve emocional', points: 14, requiresApproval: true, affectsAllowance: false, bonus_amount: 0 }),
];
