/**
 * Lê mobile/icon/avatar/*.{png,jpg,jpeg,webp} e gera avatarCatalog.generated.ts
 * Rode com: npm run sync:avatars (ou automaticamente antes de npm start)
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const AVATAR_DIR = path.join(ROOT, 'icon', 'avatar');
const OUT_FILE = path.join(ROOT, 'src', 'lib', 'avatarCatalog.generated.ts');

const IMAGE_EXT = /\.(png|jpe?g|webp)$/i;

function formatLabel(id) {
  const spaced = id
    .replace(/[_-]+/g, ' ')
    .replace(/([a-zA-ZÀ-ÿ]+)(\d+)/g, '$1 $2')
    .trim();
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

function escapeSingleQuotes(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function main() {
  if (!fs.existsSync(AVATAR_DIR)) {
    fs.mkdirSync(AVATAR_DIR, { recursive: true });
  }

  const files = fs
    .readdirSync(AVATAR_DIR)
    .filter((f) => IMAGE_EXT.test(f))
    .sort((a, b) => a.localeCompare(b, 'pt-BR'));

  const entries = files.map((file) => {
    const id = file.replace(/\.(png|jpe?g|webp)$/i, '');
    const label = formatLabel(id);
    return `  { id: '${escapeSingleQuotes(id)}', label: '${escapeSingleQuotes(label)}', source: require('../../icon/avatar/${file}') },`;
  });

  const defaultPreset = files.some((f) => f.replace(/\.(png|jpe?g|webp)$/i, '') === 'menino1')
    ? 'menino1'
    : (files[0] ? files[0].replace(/\.(png|jpe?g|webp)$/i, '') : 'menino1');

  const content = `// AUTO-GENERATED by scripts/syncAvatarCatalog.js — não editar manualmente.
// Adicione imagens em icon/avatar/ e reinicie o app (npm start).

import { ImageSourcePropType } from 'react-native';

export interface AvatarOption {
  id: string;
  label: string;
  source: ImageSourcePropType;
}

export const AVATAR_OPTIONS: AvatarOption[] = [
${entries.length ? entries.join('\n') : '  // Nenhuma imagem em icon/avatar/'}
];

export const DEFAULT_AVATAR_PRESET = '${escapeSingleQuotes(defaultPreset)}';
`;

  fs.writeFileSync(OUT_FILE, content, 'utf8');
  console.log(`[sync:avatars] ${files.length} avatar(es) → src/lib/avatarCatalog.generated.ts`);
}

main();
