const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const leafletDist = path.join(root, 'node_modules', 'leaflet', 'dist');
const output = path.join(root, 'src', 'lib', 'leafletAssets.generated.ts');

const js = fs.readFileSync(path.join(leafletDist, 'leaflet.js'), 'utf8');
let css = fs.readFileSync(path.join(leafletDist, 'leaflet.css'), 'utf8');

// Leaflet's stylesheet contains relative PNG URLs. An HTML string in a WebView
// has no asset directory, so embed those tiny images as data URLs as well.
css = css.replace(/url\(["']?(images\/[^)'" ]+)["']?\)/g, (_match, imagePath) => {
  const file = path.join(leafletDist, imagePath);
  const mime = imagePath.endsWith('.svg') ? 'image/svg+xml' : 'image/png';
  return `url(data:${mime};base64,${fs.readFileSync(file).toString('base64')})`;
});

const generated = `// Generated by scripts/syncLeafletAssets.cjs. Do not edit directly.\n` +
  `// Leaflet is packaged inside the Android app; only visible map tiles use the network.\n` +
  `export const leafletJs = ${JSON.stringify(js)};\n` +
  `export const leafletCss = ${JSON.stringify(css)};\n`;

fs.writeFileSync(output, generated);
console.log(`[sync:map] Leaflet bundled (${Math.round(generated.length / 1024)} KiB)`);
